/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import {ColumnType, Generated, Insertable, Selectable, Updateable,} from "kysely";

// export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
//     ? ColumnType<S, I | undefined, U>
//     : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
    string,
    bigint | number | string,
    bigint | number | string
>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UsersTable {
    id: Generated<string>;
    email: string;
    name: string;
    avatar?: string;
    password_hash: string;
    created_at: Generated<Timestamp>;
}

export interface WorkingAreaTable {
    id: Generated<string>;
    images: string[];
    created_at: Generated<Timestamp>;
}

export type Users = Selectable<UsersTable>;
export type NewUser = Insertable<UsersTable>;
export type UserUpdate = Updateable<UsersTable>;

export type NewWorkingArea = Insertable<WorkingAreaTable>;


export interface Database {
    users: UsersTable;
    "working-areas": WorkingAreaTable;
}
